### ISSUE TITLE
Change description (profiles) of element note (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#116]
ch.fhir.ig.ch-emed#2.1.0 /StructureDefinition-ch-emed-medicationstatement.html

### Request:
Change the description of the element **.note** (MedStat/MedReq/MedDisp/Obs) to more clearly distinguish between these elements:
* Composition.section:annotation - 'Annotation'
![image](https://user-images.githubusercontent.com/32767151/186650933-bf1843fc-3505-4809-9749-3c741afac8f5.png)
* MedStat/MedReq/MedDisp/Obs.note - 'Annotation'
![image](https://user-images.githubusercontent.com/32767151/186651248-e53addd8-5e05-4b65-848d-c2b94970e976.png)

### Proposal:
* MedicationStatement/MedicationDispense/MedicationRequest.note: 'Annotation'-> **'Patient instruction'**
* Observation.note: 'Annotation' -> **'COMMENT: the actual comment. OK/CHANGE/REFUSE/CANCEL/SUSPEND: the reason why the action was done.'**

**Comment by ziegm** [comment]
@pjolo 
Please review the proposal:
* Update description of element note:
    * [Observation.note](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-observation.html)
* Since the patient instruction is now mapped in the dosage (#120), the 'note' element has been removed from the differential for these profiles::
   * [MedicationStatement](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationstatement.html) (base for MTP usage)
   * [MedicationRequest](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationrequest.html)
   * [MedicationDispense](http://build.fhir.org/ig/hl7ch/ch-emed/branches/stu3ballot-resolution/StructureDefinition-ch-emed-medicationdispense.html)

**Comment by ziegm** [comment]
Close issue, will be merged to master with merging stu3ballotresolution branch
