### ISSUE TITLE
Medication Treatment Plan - Status on the Mediation Statement (Rob Hallowell)

### ISSUE THREAD

**Issue by rhallowell** [hl7ch/ch-emed#128]
The validator indicates the status should be set to 'completed' ; however, that doesn't make sense as 'completed' in the base HL7 specification means that the medication is no longer being taken.  Why is this fixed to that value ?  Shouldn't it be 'active'?

**Comment by qligier** [comment]
Indeed, I think it's a mapping error from CDAs, where the status code is always 'completed' (meaning it's the final version, not a draft).
The medication status represented here must be calculated (e.g. from start and stop dates), we simply can't put it in the document.

The element should be forbidden.

**Comment by ziegm** [comment]
The assumption with the CDA mapping error is reasonable. 
FHIR Core requires the status element (http://hl7.org/fhir/R4/medicationstatement.html), so it cannot be forbidden.
In the profiling aspect there are two possibilities, which one makes sense in the context of CH EMED?
- fixedValue = 'active' (like Rob proposed)
- no fixedValue, allow all values from [VS Status](http://hl7.org/fhir/R4/valueset-medication-statement-status.html)

Also applies to MedicationRequest/MedicationDispense/Observation.

**Comment by ziegm** [comment]
10.11.2022: Telco PJ/OE/MZ:
keine fixedValues setzen -> von FHIR vorgegebenes VS übernehmen

**Comment by ziegm** [comment]
@pjolo 
Please review the changes:
* Updated profiles: [MedicationStatement](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue128_status/StructureDefinition-ch-emed-medicationstatement.html) for MTP/CARD, [MedicationRequest](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue128_status/StructureDefinition-ch-emed-medicationrequest.html) => no fixedValue
* Updated examples: MedicationStatements, MedicationRequests (and Bundles which include them) => active instead of completed
* [Change Log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/issue128_status/changelog.html)

**Comment by pjolo** [comment]
Ok and the issue can be closed
