### ISSUE TITLE
Feedback about MedicationDispense

### ISSUE THREAD

**Issue by qligier** [hl7ch/ch-emed#156]
About the [MedicationDispense structure definition](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationdispense.html):

- The `ch-emed-ext-prescription` extension has the same use as `authorizingPrescription`, we should use the latter (and fix its type).
- What's the use of the `ch-emed-ext-pharmaceuticaladvice` here? Is it for the reference to PADV concerns? If so, we should probably use `supportingInformation` or `detectedIssue`.
- `substitution.wasSubstituted` and `substitution.type` are mandatory and contain the same information, which can lead to contradictions like `true + none` or `false + equivalent`. Is there something we can do here? Can we go against `wasSubstituted`'s 1..1 cardinality from the FHIR resource? Otherwise, we could remove `none` from the value set, make `type` optional and constraint its use on `true` only.

**Comment by ziegm** [comment]
1. In the currently used extension (`ch-emed-ext-prescription`) the identifier of the document and the identifier of the entry are mapped. The reference `authorizingPrescription` is used to reference the MedicationRequest from the PRE document, the info about the document would be missing.

2. Yes, if there is a PADV document in an earlier use case step. Usage of the extension (`ch-emed-pharmaceuticaladvice`) due to the same reason as point 1.

3. 1..1 for `wasSubsituted` is given through the [base spec](http://hl7.org/fhir/R4/medicationdispense.html). However, with the last proposal, it would no longer be possible to map when a drug may not be substituted (none = No substitution occurred or **is permitted**). Logical content validation cannot be done via the profile, in my opinion.

**Comment by qligier** [comment]
1. Of course, I missed that detail.
2. Indeed.
3. You're removing 'None' from the binding of `substitution.type`? That's not a bad idea; it also requires changing the cardinality back to 0..1.

**Comment by qligier** [comment]
Also, we don't have a profile equivalent to the "Pharmaceutical Advice Concern Entry Content Module" (not the "Pharmaceutical Advice Item Entry Content Module"). The _pharmaceuticalAdvice_ extension can't point to anything, it should be dropped.

**Comment by ziegm** [comment]
17.11.2022 Telco PJ/OE/MZ:
3) Need to clarify VS binding for a future version

**Comment by ziegm** [comment]
### Open point ([discussion Nov 22](https://github.com/hl7ch/ch-emed/issues/156#issuecomment-1318731739)):
3. Need to clarify VS binding for a future version


### Earlier discussion to point 3
QL: substitution.wasSubstituted and substitution.type are mandatory and contain the same information, which can lead to contradictions like true + none or false + equivalent. Is there something we can do here? Can we go against wasSubstituted's 1..1 cardinality from the FHIR resource? Otherwise, we could remove none from the value set, make type optional and constraint its use on true only.

MZ: 1..1 for wasSubsituted is given through the [base spec](http://hl7.org/fhir/R4/medicationdispense.html). However, with the last proposal, it would no longer be possible to map when a drug may not be substituted (none = No substitution occurred or is permitted). Logical content validation cannot be done via the profile, in my opinion.

QL: You're removing 'None' from the binding of substitution.type? That's not a bad idea; it also requires changing the cardinality back to 0..1.


### Overview 
MedicationDispense.subsitution 0..1
element | FHIR card. | CH EMED card. | description | value
--- | --- | --- | --- | ---
wasSubstituted | 1..1 | 1..1 | Whether a substitution was or was not performed on the dispense | true/false
type | 0..1 | 1..1 | Code signifying whether a different drug was dispensed from what was prescribed | [ActSubstanceAdminSubstitutionCode](http://terminology.hl7.org/5.0.0/ValueSet-v3-ActSubstanceAdminSubstitutionCode.html) ([preferred](http://hl7.org/fhir/R4/terminologies.html#preferred))

* E equivalent (and subcodes) - Substitution occurred or is permitted with another bioequivalent and therapeutically equivalent product.
* F formulary - This substitution was performed or is permitted based on formulary guidelines.
* N none - No substitution occurred or is permitted.

### Proposal
Should we add a tab 'Substitution' under the section 'Guidance' and describe (incl. examples) the different use cases?
* DIS: MedicationDispense.substitution.wasSubstituted/type (Whether a substitution was performed on the dispense) (this issue)
   * Substitution was performed -> true & equivalent
   * Substitution was not performed -> false & none
* PRE: MedicationRequest.substitution.allowedCodeableConcept (Whether substitution is allowed or not)
   * Substitution is allowed -> equivalent
   * Substitution is not allowed -> none
* CARD: MedicationStatement.extenstion:substitution (Whether substitution is allowed or not) ([issue](https://github.com/hl7ch/ch-emed/issues/91) from STU3 ballot)
   * Substitution is allowed -> equivalent
   * Substitution is not allowed -> none
* MTP: MedicationStatement.extenstion:substitution (Whether substitution is allowed or not)
   * Substitution is allowed -> equivalent
   * Substitution is not allowed -> none

**Comment by ziegm** [comment]
12.01. PJ, QL, OE, MZ
- remove "none" from the VS and change the binding to required
- type 0..1
- wasSubstituted = false => no type
- no guidance -> short/description

**Comment by ziegm** [comment]
@pjolo @qligier 
Please review the changes:
* [Profile MedicationDispense](http://build.fhir.org/ig/hl7ch/ch-emed/branches/156_substitution/StructureDefinition-ch-emed-medicationdispense.html)
   * [ValueSet](http://build.fhir.org/ig/hl7ch/ch-emed/branches/156_substitution/ValueSet-ActSubstanceAdminSubstitutionCode.html)
   * [Constraint](http://build.fhir.org/ig/hl7ch/ch-emed/branches/156_substitution/StructureDefinition-ch-emed-medicationdispense.html#constraints)
* Examples: [was substituted](http://build.fhir.org/ig/hl7ch/ch-emed/branches/156_substitution/MedicationDispense-MedDispTriatec-WasSubstituted.html), [was not substituted](http://build.fhir.org/ig/hl7ch/ch-emed/branches/156_substitution/MedicationDispense-MedDispTriatec-WasNotSubstituted.html)
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/156_substitution/changelog.html)

**Comment by qligier** [comment]
The current constraint (`(wasSubstituted = true and type.exists()) or (wasSubstituted = false and type.exists().not())`) makes the _type_ mandatory if it was substituted. Do we have said it was optional in that case?
I would have used the simpler one `wasSubstituted = true or (wasSubstituted = false and type.exists().not())`.

**Comment by ziegm** [comment]
> The current constraint (`(wasSubstituted = true and type.exists()) or (wasSubstituted = false and type.exists().not())`) makes the _type_ mandatory if it was substituted. Do we have said it was optional in that case? I would have used the simpler one `wasSubstituted = true or (wasSubstituted = false and type.exists().not())`.

I have adjusted this accordingly.

**Comment by qligier** [comment]
Looks good to me, thanks!

**Comment by pjolo** [comment]
For me, the changes are ok.
