### ISSUE TITLE
CH EMED Dosage (MedicationRequest) - timing - repeat too strict (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#200]
ch.fhir.ig.ch-emed#3.0.0 /StructureDefinition-ch-emed-dosage-medicationrequest.html

timing and repeat have both a min cardinality of 1. this is however quite strict, e.g. a request just for in reserve would not be possible, or an alternative timing like on a specific date. proposal: remove at least the min cardinality of 1 repeat to 0..1.

Oliver Egger, ahdis ag

**Comment by ziegm** [comment]
@oliveregger @pjolo 
Please review the changes:
* [Dosage PRE](http://build.fhir.org/ig/hl7ch/ch-emed/branches/200_dosage-pre/StructureDefinition-ch-emed-dosage-medicationrequest.html): Set min card 1 back to 0 for:
   * `Dosage.timing.repeat`
   * `Dosage.timing.repeat.when` (Also relaxed, if e.g. a complex dosage is specified as text, no other timing.repeat element (e.g. start/end date) can be specified otherwise, because the when code is then missing.)
   * Since the application schema (Anwendungsschema - z.B. 3x täglich; morgens, mittags, abends; 1x/Woche usw.) is obligatory in IPAG and is mapped to different elements in FHIR, I would suggest to relax `Dosage.timing` aswell and use a **rule** that checks if at least one element is present.
      * Dosage.text
      * Dosage.timing
      * Dosage.asNeededBoolean
* [Example](http://build.fhir.org/ig/hl7ch/ch-emed/branches/200_dosage-pre/MedicationRequest-MedReq-ComplexDosage.html): Complex Dosage (free text), in reserve, without timing
* [Change log](http://build.fhir.org/ig/hl7ch/ch-emed/branches/200_dosage-pre/changelog.html)

**Comment by oliveregger** [comment]
good for me, thanks

**Comment by pjolo** [comment]
For me also good.
