### ISSUE TITLE
Extensions (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#244]
ch.fhir.ig.ch-emed#4.0.0-ballot /extensions.html

There are two extensions, the "CH EMED Extension Treatment Plan" and the "CH EMED Extension Prescription" with the exactly same structure.
In the ch-vacd IG there exists a similar extension.

Should be not transfer the extension for referencing entities in different documents to ch-core?

Roeland Luykx (RALY GmbH)

**Comment by ziegm** [comment]
Those 4 extensions have the same structure:

- [CH EMED Extension Pharmaceutical Advice](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-pharmaceuticaladvice.html)
- [CH EMED Extension Dispense](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-dispense.html)
- [CH EMED Extension Treatment Plan](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-treatmentplan.html)
- [CH EMED Extension Prescription](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-prescription.html)

Fig.: example CH EMED Extension Pharmaceutical Advice
![image](https://github.com/hl7ch/ch-emed/assets/32767151/d1015dd5-b5c4-4877-95b5-89045fec0406)

Via the different URL you can say, where you want to use it and if more than one of this kind of extension is used, to distinguish, which document type is referenced.   

Usage of the different extensions:
- [MedicationDispense](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationdispense.html) -> PRE/PADV/MTP
- [MedicationStatment (CARD)](http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medicationstatement-card.html) -> MTP

Theoretically you could add a third nested extension in a generic one, where you could define the type (document/resource), but because we can't derive from an extension and make additional requirements to it (like for profiles), I don't see a reasonable way to do it. 
Will discuss it at the telco, may I oversee something.

**Comment by ziegm** [comment]
19.10.2023: PJ/OE/MZ
In the case of eMedication the extensions are defined by document types and having a generic document reference extension would make the IG view and rules more complicated (an additional nested extension with the document type would be needed and to be sliced). We prefer the direct currently used approach, which is also currently used in pilots.

@ralych is this fine with you?

**Comment by ziegm** [comment]
@pjolo Please review the https://github.com/hl7ch/ch-emed/pull/247

**Comment by pjolo** [comment]
Good
