### ISSUE TITLE
EDQM - RouteOfAdministration (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#254]
ch.fhir.ig.ch-emed#4.0.1 /ValueSet-edqm-routeofadministration.html

Is it correct to use status DRAFT?

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@pjolo The status does correspond to that from Art-Decor. So either we should change it in Art-Decor (and adapt it in the IG) or let it be like it is?
* http://fhir.ch/ig/ch-emed/ValueSet/ActivePharmaceuticalIngredient    
   -> https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.82&effectiveDate=2023-10-27T13:24:37&language=en-US
* http://fhir.ch/ig/ch-emed/ValueSet/edqm-routeofadministration    
   -> https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.2&effectiveDate=2022-06-08T15:42:14&language=en-US
* http://fhir.ch/ig/ch-emed/ValueSet/UnitCode    
   -> https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.2&effectiveDate=2022-06-08T15:42:14&language=en-US

**Comment by pjolo** [comment]
I have set the status of the Value Sets in Art Decor to Final 

-  https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.82&effectiveDate=2023-10-27T13:24:37&language=en-US
-  https://art-decor.org/art-decor/decor-valuesets--cdachemed-?id=2.16.756.5.30.1.1.11.2&effectiveDate=2022-06-08T15:42:14&language=en-US
- I cannot change the status of the Value Set Unit Code because the Value Set is locked by Oliver
![image](https://github.com/hl7ch/ch-emed/assets/87263053/72786cee-0e0b-4102-a54e-2206285a02e1)

**Comment by ziegm** [comment]
@oliveregger could you do an new art-decor import, that we have the updated status?

**Comment by ziegm** [comment]
@pjolo can we close that issue?

fixed with: https://github.com/hl7ch/ch-epr-term/issues/24
* https://build.fhir.org/ig/hl7ch/ch-epr-term/ValueSet-ActivePharmaceuticalIngredient.html
* https://build.fhir.org/ig/hl7ch/ch-epr-term/ValueSet-edqm-routeofadministration.html
* https://build.fhir.org/ig/hl7ch/ch-epr-term/ValueSet-UnitCode.html

**Comment by pjolo** [comment]
Yes, this issue can be closed.
