### ISSUE TITLE
Build issue (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-emed#286]
```
Generate HTML Outputs
Exception in thread "main" java.lang.Error: Duplicated element 'author' @ 'Bundle.entry[0].resource'
```

@qligier you already had a look into that, right?

As workaround, I commented out the second author in 2-5-Composition.

**Comment by qligier** [comment]
I took a look at it some time ago, the bug is here:
https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/renderers/BundleRenderer.java#L162

`comp.child("author")` should be `comp.children("author")`, but the renderDataType method won't accept a list of resources.
Maybe something like:
```java
for (final ResourceWrapper author : comp.children("author")) {
    renderDataType(status, p.param("author"), author);
}
```
could work, but I don't really have time to test it. Is there an open issue/a Zulip discussion on this already?

**Comment by ziegm** [comment]
@qligier could not find anything on zulip.
can i assign you for the issue (does not hurry at all)?

**Comment by qligier** [comment]
It was fixed: https://github.com/hapifhir/org.hl7.fhir.core/pull/1712/files

**Comment by ziegm** [comment]
Yeah, works again: https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/build.log

Thanks for having a look into it @qligier
