### ISSUE TITLE
2-3 Medication Statement with Medication Beloc Zok (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-emed#299]
ch.fhir.ig.ch-emed#5.0.0-ci-build /MedicationStatement-2-3-MedStatBeloczok.html

The Link "medication: Medication BELOC ZOK Ret Tabl 50 mg 30 Stk" points to "https://build.fhir.org/ig/hl7ch/ch-emed/MedicationStatement-2-3-MedStatBeloczok.html#hc2-3-MedStatBeloczok/Beloczok", but shoult point to the Instance BELOC ZOC of CHEMEDMedication

Marcel Hanselmann

**Comment by ziegm** [comment]
This mentioned topic appears in the current ci build in the generated narrative.
In the ballot version, the generated narrative looked different: https://fhir.ch/ig/ch-emed/5.0.0-ballot/MedicationStatement-2-3-MedStatBeloczok.html

I thinkt it is the correct link. The example 2-3-MedStatBeloczok has the Medication BELOC ZOK as contained resource. In that case, this Medication Instance does not exist in the IG as standalone instance. And the link shows to the contained medication: https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/MedicationStatement-2-3-MedStatBeloczok.html#hc2-3-MedStatBeloczok/Beloczok
But because of the reason, that this contained Medication is at the end of the page, it is not that obvious.

@lpg-tech @pjolo 
do you agree to close this issue (add it in the changelog under Issues resolved without amendment (in IG))?

**Comment by pjolo** [comment]
> This mentioned topic appears in the current ci build in the generated narrative. In the ballot version, the generated narrative looked different: https://fhir.ch/ig/ch-emed/5.0.0-ballot/MedicationStatement-2-3-MedStatBeloczok.html
> 
> I thinkt it is the correct link. The example 2-3-MedStatBeloczok has the Medication BELOC ZOK as contained resource. In that case, this Medication Instance does not exist in the IG as standalone instance. And the link shows to the contained medication: https://build.fhir.org/ig/hl7ch/ch-emed/branches/master/MedicationStatement-2-3-MedStatBeloczok.html#hc2-3-MedStatBeloczok/Beloczok But because of the reason, that this contained Medication is at the end of the page, it is not that obvious.
> 
> @lpg-tech @pjolo do you agree to close this issue (add it in the changelog under Issues resolved without amendment (in IG))?

@ziegm  From my side, the issue can be closed.
